print("hello world")
a=int(input("Podaj liczbe 1: "))
b=int(input("Podaj liczbe 2: "))
c=int(input("Podaj liczbe 3: "))
d=int(input("Podaj liczbe 4: "))
e=int(input("Podaj liczbe 5: "))
f=int(input("Podaj liczbe 6: "))
lista=(a,b,c,d,e,f)
for i in range ()